databases:
  - name: gawildlife
    databaseName: gawildlife
    user: gawildlife

services:
  - type: web
    name: gawildlife
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gawildlife
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
